Repository boostcampwm-2022/iOS01-Capsule, pull requests merged in 2022-12, with the labels that each got.

#42 목록 캡슐 셀, 개봉 화면 연동
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule/Resources/FrameResource.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/Components/CapsuleCell.swift
Labels: review

#41 앱 데이터 매니저 구현
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule/Assets.xcassets/Images/Contents.json
  SpaceCapsule/SpaceCapsule/Assets.xcassets/Images/openableCapsule.imageset/Contents.json
  SpaceCapsule/SpaceCapsule/Assets.xcassets/Images/openableCapsule.imageset/capsule.png
  SpaceCapsule/SpaceCapsule/Assets.xcassets/Images/unopenableCapsule.imageset/Contents.json
  SpaceCapsule/SpaceCapsule/Assets.xcassets/Images/unopenableCapsule.imageset/lockedCapsule.png
  SpaceCapsule/SpaceCapsule/Base/Refreshable.swift
  SpaceCapsule/SpaceCapsule/Components/CustomScrollView.swift
  SpaceCapsule/SpaceCapsule/Components/Map/CustomAnnotation.swift
  SpaceCapsule/SpaceCapsule/Components/Map/CustomAnnotationView.swift
  SpaceCapsule/SpaceCapsule/Components/Map/CustomMapView.swift
  SpaceCapsule/SpaceCapsule/Components/Map/CustomRefreshableMapView.swift
  SpaceCapsule/SpaceCapsule/Extensions/UIImage+.swift
  SpaceCapsule/SpaceCapsule/Manager/AppDataManager.swift
  SpaceCapsule/SpaceCapsule/Manager/Firebase/FirestoreManager.swift
  SpaceCapsule/SpaceCapsule/Manager/KingReceiver/Extensions/KingReceiver+UIImageView.swift
  SpaceCapsule/SpaceCapsule/Manager/LocationManager.swift
  SpaceCapsule/SpaceCapsule/Manager/NetworkManager.swift
  SpaceCapsule/SpaceCapsule/Model/Address.swift
  SpaceCapsule/SpaceCapsule/Model/Capsule.swift
  SpaceCapsule/SpaceCapsule/Scene/Auth/Nickname/NicknameViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleCreate/CapsuleLocate/CapsuleLocateView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleCreate/CapsuleLocate/CapsuleLocateViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleMap/CapsuleMapViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleMap/CapsuleMapViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Profile/ProfileView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Profile/ProfileViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Profile/ProfileViewModel.swift
  SpaceCapsule/SpaceCapsule/running.gpx
Labels: review

#44 Feature home
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule/Components/Theme/ThemeThumbnailImageView.swift
  SpaceCapsule/SpaceCapsule/Resources/FrameResource.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/Components/ListCapsuleCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/Components/ListCapsuleCellModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/CarouselCollectionViewFlowLayout.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/Components/HomeCapsuleCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/Components/HomeCapsuleCellModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeViewModel.swift
Labels: feature, review

#46 목록 캡슐 리팩토링
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule/Resources/AnimationResource.swift
  SpaceCapsule/SpaceCapsule/Resources/FrameResource.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/SortPolicySelection/SortPolicySelectionCoordinator.swift
Labels: review

#45 디테일 뷰 UI 구현
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule/App/AppCoordinator.swift
  SpaceCapsule/SpaceCapsule/Resources/FrameResource.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/CapsuleDetailCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/CapsuleDetailView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/CapsuleDetailViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/CapsuleDetailViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/Componenets/DetailImageCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/Componenets/DetailImageCollectionView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/Componenets/DetailImageFlowLayout.swift
Labels: feature, review

#49 목록 앱 새로고침 구현
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule/Components/Theme/ThemeThumbnailImageView.swift
  SpaceCapsule/SpaceCapsule/Manager/LocationManager.swift
  SpaceCapsule/SpaceCapsule/Resources/AnimationResource.swift
  SpaceCapsule/SpaceCapsule/Resources/FrameResource.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleClose/CapsuleCloseView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleClose/CapsuleCloseViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/Components/ListCapsuleCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/Components/ListCapsuleCellModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/Components/HomeCapsuleCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/Components/HomeCapsuleCellModel.swift
Labels: review

#53 Feature capsule list
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule/Manager/LocationManager.swift
  SpaceCapsule/SpaceCapsule/Resources/FrameResource.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleAccessCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/Components/ListCapsuleCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/Components/ListCapsuleCellItem.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/Components/UnOpenable.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/Components/HomeCapsuleCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeViewModel.swift
Labels: hotfix, review, refactor

#59 프로필 구현
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule/Base/Coordinator.swift
  SpaceCapsule/SpaceCapsule/Components/CustomTabBarController.swift
  SpaceCapsule/SpaceCapsule/Components/Theme/ProfileButton.swift
  SpaceCapsule/SpaceCapsule/Manager/Firebase/FirebaseAuthManager.swift
  SpaceCapsule/SpaceCapsule/Manager/Firebase/FirestoreManager.swift
  SpaceCapsule/SpaceCapsule/Resources/FrameResource.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Profile/ProfileCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Profile/ProfileView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Profile/ProfileViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Profile/ProfileViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/TabBarCoordinator.swift
Labels: feature

#71 캡슐 어노테이션 클릭 시 상세화면으로 이동
  SpaceCapsule/SpaceCapsule/Extensions/MKMapView+Rx.swift
  SpaceCapsule/SpaceCapsule/Model/GeoPoint.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleAccessCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleCreate/CapsuleLocate/CapsuleLocateViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleMap/CapsuleMapCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleMap/CapsuleMapViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleMap/CapsuleMapViewModel.swift
Labels: feature

#73 [지도] 캡슐 어노테이션 탭 콜아웃 구현
  SpaceCapsule/SpaceCapsule/Components/Map/CustomAnnotation.swift
  SpaceCapsule/SpaceCapsule/Components/Map/CustomAnnotationView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/CapsuleDetailViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleMap/CapsuleMapViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleMap/CapsuleMapViewModel.swift
Labels: feature

#75 이미지 상세보기 & 확대 기능 추가
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleCreate/CapsuleCreateCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleCreate/CapsuleCreateViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleCreate/CapsuleCreateViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/DetailImage/DetailImageCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/DetailImage/DetailImageView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/DetailImage/DetailImageViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/DetailImage/DetailImageViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/DetailImage/ZoomableImageCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/DetailImage/ZoomableImageView.swift
Labels: review

#81 캡슐 상세 페이지 완성
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule/Manager/Firebase/FirestoreManager.swift
  SpaceCapsule/SpaceCapsule/Resources/FrameResource.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/CapsuleDetailCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/CapsuleDetailView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/CapsuleDetailViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/CapsuleDetailViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/CapsuleSettings/CapsuleSettingsCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/CapsuleSettings/CapsuleSettingsView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/CapsuleSettings/CapsuleSettingsViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/CapsuleSettings/CapsuleSettingsViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/Componenets/DetailImageCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/Componenets/DetailImageFlowLayout.swift
Labels: feature, review

#83 [전체] 푸시알림 구현
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SpaceCapsule/SpaceCapsule/App/AppDelegate.swift
  SpaceCapsule/SpaceCapsule/Info.plist
  SpaceCapsule/SpaceCapsule/Manager/NotificationManager.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Profile/ProfileView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Profile/ProfileViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Profile/ProfileViewModel.swift
Labels: feature, review

#89 [홈 화면] 기준에 따라 특정 캡슐 출력
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule/App/AppCoordinator.swift
  SpaceCapsule/SpaceCapsule/Components/Theme/ThemeThumbnailImageView.swift
  SpaceCapsule/SpaceCapsule/Extensions/Date+.swift
  SpaceCapsule/SpaceCapsule/Manager/UserDefaultsManager.swift
  SpaceCapsule/SpaceCapsule/Resources/FrameResource.swift
  SpaceCapsule/SpaceCapsule/Scene/Auth/AuthCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/Auth/Nickname/NicknameCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/Auth/Nickname/NicknameViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/Auth/Nickname/NicknameViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/Auth/SignIn/SignInCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/Auth/SignIn/SignInViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleCreate/CapsuleCreateViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleCreate/DatePicker/DatePickerViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/Components/ListCapsuleCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleMap/CapsuleMapViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/CarouselCollectionViewFlowLayout.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/Components/HomeCapsuleCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/Components/HomeCapsuleCellItem.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/Components/HomeCapsuleCellModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeViewModel.swift
Labels: review

#92 캡슐 상세화면 버그 수정
  SpaceCapsule/SpaceCapsule/Resources/FrameResource.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/CapsuleDetailView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/CapsuleDetailViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/Componenets/DetailImageCell.swift
Labels: bug, review

#93 자잘한 버그 수정 및 리팩토링
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule/Assets.xcassets/AppIcon.appiconset/114.png
  SpaceCapsule/SpaceCapsule/Assets.xcassets/AppIcon.appiconset/120.png
  SpaceCapsule/SpaceCapsule/Assets.xcassets/AppIcon.appiconset/180.png
  SpaceCapsule/SpaceCapsule/Assets.xcassets/AppIcon.appiconset/29.png
  SpaceCapsule/SpaceCapsule/Assets.xcassets/AppIcon.appiconset/40.png
  SpaceCapsule/SpaceCapsule/Assets.xcassets/AppIcon.appiconset/57.png
  SpaceCapsule/SpaceCapsule/Assets.xcassets/AppIcon.appiconset/58.png
  SpaceCapsule/SpaceCapsule/Assets.xcassets/AppIcon.appiconset/60.png
  SpaceCapsule/SpaceCapsule/Assets.xcassets/AppIcon.appiconset/80.png
  SpaceCapsule/SpaceCapsule/Assets.xcassets/AppIcon.appiconset/87.png
  SpaceCapsule/SpaceCapsule/Assets.xcassets/AppIcon.appiconset/Contents.json
  SpaceCapsule/SpaceCapsule/Components/BlurEffectView.swift
  SpaceCapsule/SpaceCapsule/Components/CustomNavigationController.swift
  SpaceCapsule/SpaceCapsule/Components/Theme/ProfileButton.swift
  SpaceCapsule/SpaceCapsule/Manager/LocationManager.swift
  SpaceCapsule/SpaceCapsule/Resources/FrameResource.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/CapsuleDetailCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleClose/CapsuleCloseView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/Components/ListCapsuleCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/Components/UnOpenable.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/DetailImage/DetailImageViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/Components/HomeCapsuleCell.swift
Labels: bug, review, refactor

#94 [feat] 이미지 상세 뷰 그라데이션 추가 (#72)
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule/Scene/TabBar/DetailImage/DetailImageView.swift
Labels: review

#98 이미지 처리 및 캐싱 모듈 수정
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule/Components/Map/CustomAnnotationView.swift
  SpaceCapsule/SpaceCapsule/Extensions/UIImage+.swift
  SpaceCapsule/SpaceCapsule/Manager/KingReceiver/Extensions/KingReceiver+UIImageView.swift
  SpaceCapsule/SpaceCapsule/Manager/KingReceiver/Extensions/NSCache+subscript.swift
  SpaceCapsule/SpaceCapsule/Manager/KingReceiver/Extensions/UIImage+resize.swift
  SpaceCapsule/SpaceCapsule/Manager/KingReceiver/ImageCache/MemoryImageCache.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleCreate/Components/AddImageCell.swift
Labels: review

#102 지도 버그 수정
  SpaceCapsule/SpaceCapsule/Extensions/MKMapView+Rx.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleMap/CapsuleMapCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleMap/CapsuleMapViewController.swift
Labels: review

#104 [밀봉/개봉 화면] 버그 수정
  SpaceCapsule/SpaceCapsule/Resources/AnimationResource.swift
  SpaceCapsule/SpaceCapsule/Resources/FrameResource.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleClose/CapsuleCloseView.swift
Labels: bug, review

#105 캡슐 추가, 프로필 버그 수정
  SpaceCapsule/SpaceCapsule/Manager/KingReceiver/Extensions/KingReceiver+UIImageView.swift
  SpaceCapsule/SpaceCapsule/Manager/KingReceiver/Extensions/UIImage+resize.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleCreate/CapsuleCreateView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleCreate/CapsuleCreateViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleCreate/Components/AddImageCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Profile/ProfileViewController.swift
Labels: bug, review

#106 회원 탈퇴 애플토큰 revoke 구현
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SpaceCapsule/SpaceCapsule/Extensions/Data+.swift
  SpaceCapsule/SpaceCapsule/Extensions/Date+.swift
  SpaceCapsule/SpaceCapsule/Manager/Firebase/FirebaseAuthManager.swift
  SpaceCapsule/SpaceCapsule/Manager/Firebase/FirebaseStorageManager.swift
  SpaceCapsule/SpaceCapsule/Manager/Firebase/FirestoreManager.swift
  SpaceCapsule/SpaceCapsule/Manager/UserDefaultsManager.swift
  SpaceCapsule/SpaceCapsule/Scene/Auth/SignIn/SignInViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/CapsuleSettings/CapsuleSettingsViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Profile/ProfileViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Profile/ProfileViewModel.swift
Labels: feature, review

#109 [홈] 버그 수정
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/Components/HomeCapsuleCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/Components/HomeCapsuleCellItem.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeViewModel.swift
Labels: bug, review

#113 [목록] 버그 수정 및 기능 구현
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeViewModel.swift
Labels: bug, feature, review

#115 [캡슐 개봉/밀봉] 버그 수정
  SpaceCapsule/SpaceCapsule/Manager/Firebase/FirestoreManager.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleClose/CapsuleCloseView.swift
Labels: hotfix, review

#114 [홈] 버그 수정
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeViewController.swift
Labels: bug, review

#117 [전체] 버그 수정 및 리팩토링
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule/App/AppCoordinator.swift
  SpaceCapsule/SpaceCapsule/Base/MovableToCapsuleAccess.swift
  SpaceCapsule/SpaceCapsule/Base/Refreshable.swift
  SpaceCapsule/SpaceCapsule/Base/ViewModel/CapsuleCellItemNeedable.swift
  SpaceCapsule/SpaceCapsule/Components/Theme/ThemeLabel.swift
  SpaceCapsule/SpaceCapsule/Extensions/Calendar+.swift
  SpaceCapsule/SpaceCapsule/Info.plist
  SpaceCapsule/SpaceCapsule/Scene/Auth/SignIn/SignInViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/Auth/SignIn/SignInViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/Components/ListCapsuleCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleMap/CapsuleMapCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleMap/CapsuleMapView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleMap/CapsuleMapViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleMap/CapsuleMapViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/Components/HomeCapsuleCellItem.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeCoordinator.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeViewModel.swift
Labels: bug, review, refactor

#120 [목록] 정렬 SortPolicy description 표현 수정
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/SortPolicySelection/Components/SortPolicy.swift
Labels: hotfix, review

#124 KingReceiver SPM 으로 변경
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SpaceCapsule/SpaceCapsule/Components/Map/CustomAnnotationView.swift
  SpaceCapsule/SpaceCapsule/Manager/KingReceiver/Extensions/KingReceiver+UIImageView.swift
  SpaceCapsule/SpaceCapsule/Manager/KingReceiver/Extensions/NSCache+subscript.swift
  SpaceCapsule/SpaceCapsule/Manager/KingReceiver/Extensions/UIImage+resize.swift
  SpaceCapsule/SpaceCapsule/Manager/KingReceiver/ImageCache/DiskImageCache.swift
  SpaceCapsule/SpaceCapsule/Manager/KingReceiver/ImageCache/ImageCache.swift
  SpaceCapsule/SpaceCapsule/Manager/KingReceiver/ImageCache/ImageCacheFactory.swift
  SpaceCapsule/SpaceCapsule/Manager/KingReceiver/ImageCache/MemoryImageCache.swift
  SpaceCapsule/SpaceCapsule/Manager/KingReceiver/ImageCache/NoneImageCache.swift
  SpaceCapsule/SpaceCapsule/Manager/KingReceiver/KingReceiver.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleDetail/CapsuleDetailViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleClose/CapsuleCloseView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleCreate/Components/AddImageCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/Components/ListCapsuleCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/DetailImage/ZoomableImageCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/Components/HomeCapsuleCell.swift
Labels: review, refactor

#126 [프로필] 회원 탈퇴 오류 수정 및 Storage 사진 삭제 구현
  SpaceCapsule/SpaceCapsule/Error/FBStorageError.swift
  SpaceCapsule/SpaceCapsule/Manager/Firebase/FirebaseAuthManager.swift
  SpaceCapsule/SpaceCapsule/Manager/Firebase/FirebaseStorageManager.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Profile/ProfileView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Profile/ProfileViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Profile/ProfileViewModel.swift
Labels: bug, feature, refactor

#128 [전체] Auth Key Plist에 넣기
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule/AuthKey.plist
  SpaceCapsule/SpaceCapsule/Extensions/SpaceCapsule+Bundle.swift
  SpaceCapsule/SpaceCapsule/Manager/Firebase/FirebaseAuthManager.swift
  SpaceCapsule/SpaceCapsule/Manager/Firebase/FirebaseStorageManager.swift
Labels: refactor

#129 리팩토링 (밀봉, 개봉, 홈, Capsule)
  SpaceCapsule/SpaceCapsule.xcodeproj/project.pbxproj
  SpaceCapsule/SpaceCapsule.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SpaceCapsule/SpaceCapsule/Base/ViewModel/CapsuleCellItemNeedable.swift
  SpaceCapsule/SpaceCapsule/Components/BlurEffectView.swift
  SpaceCapsule/SpaceCapsule/Components/CapsuleThumbnailView.swift
  SpaceCapsule/SpaceCapsule/Components/Theme/ThemeButton.swift
  SpaceCapsule/SpaceCapsule/Components/Theme/ThumbnailImageView.swift
  SpaceCapsule/SpaceCapsule/Manager/LocationManager.swift
  SpaceCapsule/SpaceCapsule/Scene/Auth/Nickname/NicknameView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAccess/CapsuleOpen/CapsuleOpenViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleClose/CapsuleCloseView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleClose/CapsuleCloseViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleCreate/CapsuleLocate/CapsuleLocateView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleCreate/CapsuleLocate/CapsuleLocateViewController.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleAdd/CapsuleCreate/DatePicker/DatePickerView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/CapsuleListViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/Components/ListCapsuleCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/Components/ListCapsuleCellItem.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/Components/LockImageView.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/CapsuleList/Components/UnOpenable.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/Components/HomeCapsuleCell.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/Components/HomeCapsuleCellItem.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeViewModel.swift
  SpaceCapsule/SpaceCapsule/Scene/TabBar/Profile/ProfileViewController.swift
Labels: review, refactor
